### ISSUE TITLE
Highlight your disk on game start.

### ISSUE THREAD

**Issue by AndyLnd** [AndyLnd/the-standup-games#13]
It would be easier to dive right into the game if you didn't have to go looking for your disk before starting to move.

**Comment by rmlevangelio** [comment]
@AndyLnd is it more like a blinking effect type of highlight or highlight your character all through out the whole game? ?

**Comment by AndyLnd** [comment]
@rmlevangelio The way i imagine it would be just to point you to your character at the start of the game, throughout the match nothing would change. I am not quite sure yet what it will look like.

**Comment by AndyLnd** [comment]
https://github.com/AndyLnd/the-standup-games/commit/5c9404715cca3fed96f9d97d6bad21760a56b170
