### ISSUE TITLE
Mobile support 

### ISSUE THREAD

**Issue by rhys-the-davies** [AndyLnd/the-standup-games#14]
We should have mobile support!!! 

I'm sitting next to Anna while she plays on her computer but can't participate because my laptop is in the other room 😭

Although good luck with implementing arrow keys or something? Because if the movement is touch/drag based the mobile version will make the movement smoother 

Anyway.

**Comment by AndyLnd** [comment]
@rhys-the-davies https://github.com/AndyLnd/the-standup-games/commit/68948e347494871afd68660ae19618b1a40767b0 :)
