### ISSUE TITLE
Host showing up double

### ISSUE THREAD

**Issue by alexandrulesi** [AndyLnd/the-standup-games#2]
![image](https://user-images.githubusercontent.com/37101969/174757391-fd1c58e9-f4d6-4861-a1ae-37e7a3ffb9ae.png)

Steps To Reproduce:
- Go to https://thestandup.games/rumble
- Press Host Game

Expected behavior:
- New game is hosted and you join once

Actual behavior:
- New game is hosted and you join twice

Notes:
We managed to get around it by allowing others to join and then having the host refresh the page. Sometimes though if you refresh the page as a host it gets stuck on "loading ..."

**Comment by AndyLnd** [comment]
Thanks for reporting :)
This should be fixed in https://github.com/AndyLnd/the-standup-games/commit/ce41adf5d58e9eaed787555d1796101844236b13.
