### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by bennycode** [AndyLnd/the-standup-games#3]
After a round of "Sumo" is finished, it would be nice to see a scoreboard that shows the names of players on their ranks:

1st Michael
2nd Priscilla
3rd Andy
4th Benny

**Comment by AndyLnd** [comment]
That is what the screen after the match actually shows. But I agree that the "styling" is not really there. Will improve.

**Comment by AndyLnd** [comment]
Done in https://github.com/AndyLnd/the-standup-games/commit/1fd10e9e5e6dd5b763545998a90375b25d0c45be
