### ISSUE TITLE
Add link to GitHub repo from website

### ISSUE THREAD

**Issue by bennycode** [AndyLnd/the-standup-games#5]
To find the source code it would be cool if https://thestandup.games/ would show a badge to link to the GitHub repository:

![image](https://user-images.githubusercontent.com/469989/203010231-8e04604f-5b48-4ee9-a282-bad198970ecf.png)

**Comment by AndyLnd** [comment]
Absolutely!

**Comment by AndyLnd** [comment]
Solved in https://github.com/AndyLnd/the-standup-games/commit/95cf74725c26a75eae4cfdcfd652c6231d75f78b
