### ISSUE TITLE
Game stays in loading state when joining an already running game

### ISSUE THREAD

**Issue by bennycode** [AndyLnd/the-standup-games#7]
I tried to join this URL (when the game already started): https://thestandup.games/rumble/lvWwJxit0

The game was showing me then a "loading..." screen but in the JS console I could see a `ServerError` with the message "Game is already in session". It would be nice if I could see this message instead of a misleading "loading".

## Screenshot

![image](https://user-images.githubusercontent.com/469989/213129967-371dcedb-82d6-401b-b7ce-1d9a8a986602.png)

**Comment by AndyLnd** [comment]
I will add a screen that tells you that the game is already running and a link back to the home screen.
